web/scalica/micro/urls.py
from django.conf.urls import include, url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^stream/(?P<user_id>[0-9]+)/$', views.stream, name='stream'),
    url(r'^post/$', views.post, name='post'),
    url(r'^addGroup/$', views.addGroup, name='addGroup'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^grouplist/$', views.getGroups, name='getGroups'),
    url(r'^memberlist/$', views.getMembers, name='getMembers'),
    #url(r'^grouplist/$', views.getGroups, name='getGroups'),
    url(r'^register/$', views.register, name='register'),
    url(r'^addToGroup/$', views.addMemberToGroup, name='addToGroup'),
    #url(r'^userslist/$', views.getAllUsers, name='getUsers'),
    url(r'^deleteGroup/$', views.deleteGroup, name='delete'),
    url(r'^deleteMember/$', views.deleteMember, name='deleteMember'),
    url(r'^userid/$', views.getUserId, name='deleteMember'),
    url('^', include('django.contrib.auth.urls'))
]

web/scalica/scalica/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^micro/', include('micro.urls', namespace="micro")),
    url(r'^admin/', include(admin.site.urls)),
]

web/scalica/micro/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django import forms
from django.forms import ModelForm, TextInput

class Post(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL)
  visibility = models.IntegerField(default=1)
  #group_ID = models.IntegerField(default=0)
  group_name = models.CharField(max_length=256, blank=True)
  text = models.CharField(max_length=256, default="")
  pub_date = models.DateTimeField('date_posted')
  def __str__(self):
    if len(self.text) < 16:
      desc = self.text
    else:
      desc = self.text[0:16]
    return self.user.username + ':' + desc

class Following(models.Model):
  follower = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="user_follows")
  followee = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="user_followed")
  follow_date = models.DateTimeField('follow data')
  def __str__(self):
    return self.follower.username + "->" + self.followee.username

# Model Forms
class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = ('text','visibility','group_name')
    VISIBILITY_CHOICES = (
      (1, "Public"),
      (2, "Followers"),
      (3, "Group"),
      (4, "Private"),
      )
    widgets = {
      'text': TextInput(attrs={'id' : 'input_post'}),
      'visibility': forms.Select(choices=VISIBILITY_CHOICES,attrs={'class': 'form-control'}),
      'group_name': TextInput()#attrs={'id' : 'input_group'})
    }

class FollowingForm(ModelForm):
  class Meta:
    model = Following
    fields = ('followee',)

class MyUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm.Meta):
    help_texts = {
      'username' : '',
    }

web/scalica/micro/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from .models import Following, Post, FollowingForm, PostForm, MyUserCreationForm
import grpc
import groups_pb2
import groups_pb2_grpc
import groupDB_pb2
import groupDB_pb2_grpc



#import sys


import models


# Group manager RPC
channel = grpc.insecure_channel("localhost:50051")
stub = groups_pb2_grpc.Groups_ManagerStub(channel)

channel2 = grpc.insecure_channel("localhost:50052")
stub2 = groupDB_pb2_grpc.databaseStub(channel2)

# Anonymous views
#################
def index(request):
  if request.user.is_authenticated():
    return home(request)
  else:
    return anon_home(request)

def anon_home(request):
  return render(request, 'micro/public.html')



def stream(request, user_id):  
  # See if to present a 'follow' button
  form = None
  if request.user.is_authenticated() and request.user.id != int(user_id):
    try:
      f = Following.objects.get(follower_id=request.user.id,
                                followee_id=user_id)
    except Following.DoesNotExist:
      form = FollowingForm
  user = User.objects.get(pk=user_id)
  post_list = Post.objects.filter(user_id=user_id).order_by('-pub_date')

  # FILTER POSTS DEPENDING ON VISIBILITY SETTINGS

  # Filter follower-only posts
  if request.user.id != int(user_id):
    try:
      f = Following.objects.get(follower_id=request.user.id,
                                followee_id=user_id)
    except Following.DoesNotExist:
      post_list = post_list.exclude(visibility=2)

  # Filter group posts
  group_posts = post_list.filter(visibility=3)
  for post in group_posts:
    post_gid = stub2.getGroupId(groupDB_pb2.getGroupRequest(userId=post.user.id, groupName=post.group_name)).groupId

    if request.user.id != int(user_id) and stub.Contains(groups_pb2.ContainsRequest(group_id=str(post_gid), user_id=str(request.user.id))).result != 1:
      post_list = post_list.exclude(id=post.id)

  # Filter private posts
  if request.user.id != int(user_id):
    post_list = post_list.exclude(visibility=4)

  paginator = Paginator(post_list, 10)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer, deliver first page.
    posts = paginator.page(1) 
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    posts = paginator.page(paginator.num_pages)
  context = {
    'posts' : posts,
    'stream_user' : user,
    'form' : form,
  }
  return render(request, 'micro/stream.html', context)

def register(request):
  if request.method == 'POST':
    form = MyUserCreationForm(request.POST)
    new_user = form.save(commit=True)
    # Log in that user.
    user = authenticate(username=new_user.username,
                        password=form.clean_password2())
    if user is not None:
      login(request, user)
    else:
      raise Exception
    return home(request)
  else:
    form = MyUserCreationForm
  return render(request, 'micro/register.html', {'form' : form})

# Authenticated views
#####################
@login_required
def home(request):
  '''List of recent posts by people I follow'''
  try:
    my_post = Post.objects.filter(user=request.user).order_by('-pub_date')[0]
  except IndexError:
    my_post = None

  # Exclude the user's posts
  post_list = Post.objects.exclude(user_id=request.user.id)

  # Filter posts to people the user follows
  for post in post_list:
    try:
      f = Following.objects.get(follower_id=request.user.id,
                                followee_id=post.user.id)
    except Following.DoesNotExist:
      post_list = post_list.exclude(id=post.id)

  # FILTER POSTS DEPENDING ON VISIBILITY SETTINGS

  # Filter group posts
  group_posts = post_list.filter(visibility=3)
  for post in group_posts:
    post_gid = stub2.getGroupId(groupDB_pb2.getGroupRequest(userId=post.user.id, groupName=post.group_name)).groupId

    if stub.Contains(groups_pb2.ContainsRequest(group_id=str(post_gid), user_id=str(request.user.id))).result != 1:
      post_list = post_list.exclude(id=post.id)

  # Filter private posts
  post_list = post_list.exclude(visibility=4)

  post_list.order_by('-pub_date')[0:10]

  context = {
    'post_list': post_list,
    'my_post' : my_post,
    'post_form' : PostForm
  }
  return render(request, 'micro/home.html', context)

# Allows to post something and shows my most recent posts.
@login_required
def post(request):
  if request.method == 'POST':
    form = PostForm(request.POST)
    new_post = form.save(commit=False)
    new_post.user = request.user
    new_post.pub_date = timezone.now()
    new_post.save()
    return home(request)
  else:
    form = PostForm
  return render(request, 'micro/post.html', {'form' : form})

@login_required
def follow(request):
  if request.method == 'POST':
    form = FollowingForm(request.POST)
    new_follow = form.save(commit=False)
    new_follow.follower = request.user
    new_follow.follow_date = timezone.now()
    new_follow.save()
    return home(request)
  else:
    form = FollowingForm
  return render(request, 'micro/follow.html', {'form' : form})

@login_required
def settings(request):
  return render(request, 'micro/settings.html')

@login_required
def addGroup(request):
  #here i wanna call your method here
  groupName = request.POST.get('newgroup')
  print("group name top "+groupName)
  with grpc.insecure_channel('localhost:50052') as channel2:
    stub2 = groupDB_pb2_grpc.databaseStub(channel2)
    stub2.addGroup(groupDB_pb2.addGroupRequest(userId = request.user.id, groupName = groupName))
    print(stub2.getGroupNames(groupDB_pb2.getGroupNamesRequest(userId = request.user.id)))

  with grpc.insecure_channel('localhost:50052') as channel2:
    stub2 = groupDB_pb2_grpc.databaseStub(channel2)
    print("group name from user "+groupName)
    groupID = stub2.getGroupId(groupDB_pb2.getGroupRequest(groupName = groupName, userId = request.user.id))
    print(stub2.getGroupNames(groupDB_pb2.getGroupNamesRequest(userId = request.user.id)))
    print('group id is' + str(groupID.groupId))

  with grpc.insecure_channel('localhost:50051') as channel:
    stub = groups_pb2_grpc.Groups_ManagerStub(channel)
    stub.AddMember(groups_pb2.AddMemberRequest(group_id = str(groupID.groupId), user_id = str(request.user.id)))
  return render(request, 'micro/settings.html')


@login_required
def getGroups(request):
  #here i wanna call your method here
  with grpc.insecure_channel('localhost:50052') as channel2:
    stub = groupDB_pb2_grpc.databaseStub(channel2)
    groups = stub.getGroupNames(groupDB_pb2.getGroupNamesRequest(userId = request.user.id))
    print(groups.groupNames)
    groups = str(groups.groupNames)
    items = groups.split(',')
    print(items)
  return render(request, 'micro/settings.html', {'items': items})

@login_required
def deleteGroup(request):
  #here i wanna call your method here
  groupName = request.POST.get('groupp')
  with grpc.insecure_channel('localhost:50052') as channel2:
    stub2 = groupDB_pb2_grpc.databaseStub(channel2)
    tempId = stub2.getGroupId(groupDB_pb2.getGroupRequest(userId = int(request.user.id), groupName = str(groupName))).groupId
    stub2.deleteGroup(groupDB_pb2.deleteGroupRequest(groupName = str(groupName), userId = int(request.user.id)))
  with grpc.insecure_channel('localhost:50051') as channel:
	  stub =  groups_pb2_grpc.Groups_ManagerStub(channel)
	  stub.DeleteGroup(groups_pb2.DeleteGroupRequest(group_id = str(tempId))).result
  return render(request, 'micro/settings.html')


@login_required
def getMembers(request):
  #here i wanna call your method here
  with grpc.insecure_channel('localhost:50052') as channel2:
    stub2 = groupDB_pb2_grpc.databaseStub(channel2)
    print(request.POST.get('usersingroup'))
    groupID = stub2.getGroupId(groupDB_pb2.getGroupRequest(groupName = request.POST.get('usersingroup'), userId = request.user.id))
    print(str(groupID.groupId))
  with grpc.insecure_channel('localhost:50051') as channel:
    stub = groups_pb2_grpc.Groups_ManagerStub(channel)
    members = stub.AllMembers(groups_pb2.AllMembersRequest(group_id = str(groupID.groupId)))
    members = members.result
    print(members)
  return render(request, 'micro/settings.html',{'members': members})

#@login_required
#def addMemberToGroup(request):
  #here i wanna call your method here
  #groupID = getGroupID(request.POST.get('groups2'),request.user.id)
  #with grpc.insecure_channel('localhost:50051') as channel:
   # stub = groups_pb2_grpc.Groups_ManagerStub(channel)
   # stub.AddMember(groups_pb2.AddMemberRequest(userId = request.POST.get('user'), groupId = groupID))
  #return render(request, 'micro/settings.html')

@login_required
def getGroupID(request, request2):
  with grpc.insecure_channel('localhost:50052') as channel2:
    stub = groupDB_pb2_grpc.databaseStub(channel2)
    groupID = stub.getGroupId(groupDB_pb2.getGroupRequest(groupName = request, userId = request2))
  return groupID

def deleteMember(request):
  with grpc.insecure_channel('localhost:50052') as channel2:
    stub2 = groupDB_pb2_grpc.databaseStub(channel2)
    print("this is what i entered "+request.POST.get('group'))
    groupID = stub2.getGroupId(groupDB_pb2.getGroupRequest(groupName = request.POST.get('group'), userId = request.user.id)).groupId
    print(groupID)
  with grpc.insecure_channel('localhost:50051') as channel:
    stub = groups_pb2_grpc.Groups_ManagerStub(channel)
    print("this is my member "+ str(request.POST.get('user')))
    stub.RemoveMember(groups_pb2.RemoveMemberRequest(group_id = str(groupID), user_id = str(request.POST.get('user'))))
    print(request.user.id)
  return render(request, 'micro/settings.html')

@login_required

web/scalica/micro/templates/micro/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'micro/style.css' %}" />
  <title>Scalica</title>
</head> 
<body>
  <div id="header">

      



    {% if user.is_authenticated %}
      {{ user.username }}
      <a href="{% url 'micro:logout' %}">Log Out</a>
    {% else %}
      <a href="{% url 'micro:login' %}">Log In</a>
    {% endif %}
    {% block header %}{% endblock header %}


    <nav>
	        

        <ul id = "mainNav">
        <a href="/micro/">
          <li class = "navItem">
            Home
          </li>
        </a>

        <a href="/micro/follow/">
          <li class = "navItem">
            Follow
          </li>
        </a>


      </ul>
    
    </nav>
  </div>
  <div id="sidebar">
    {% block sidebar %}{% endblock sidebar %}
  </div>
  <div id="content">
    {% block content %}{% endblock content %}
  </div>
  <div id="footer">
    <p>Copyright Scalica</p>
    {% block footer %}{% endblock footer %}
  </div>
</body>
</html>

web/scalica/micro/templates/micro/base_simple.html
{% extends "base.html" %}
{% block page %}
<div class="wrapper">
<div id="content" class="clearfix">
{% block content %}
{% endblock %}
</div>
</div>
{% endblock %}

web/scalica/micro/templates/micro/follow.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/follow/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/home.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ user.username }} <p>
{% endblock %}
{% block content %}
<div id="status">
{% if my_post %}
 {{ my_post.text }} ({{ my_post.pub_date|naturaltime }})
{% endif %}
</div>
<div id="post">
  <form action="/micro/post/" method="post">
    {% csrf_token %}
    {{ post_form }}
    <input type="submit" value="Post" />
  </form>
</div>
<p><br><br><br><br><br>
<div>
{% if post_list %}
  <table id="postlist">
    {% for post in post_list %}
      <tr>
        <td>
          <img src="{% static "micro/images/user_s.png" %}" alt="Generic User"/>
        </td>
        <td>
          {{ post.text }}
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <a href="{% url 'micro:stream' post.user_id %}">
            {{ post.user.username }}
          </a>
          ({{ post.pub_date|naturaltime }})
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No posts are available.</p>
{% endif %}
</div>
{% endblock %}

web/scalica/micro/templates/micro/post.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/post/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/public.html
{% extends "micro/base.html" %}
{% block content %}
  <h1>Welcome to Scalica</h1></br>
  New Users: <a href="{% url 'micro:register' %}">Register</a> </br>
  Existing Users: <a href="{% url 'micro:login' %}">Log In</a>
{% endblock %}

web/scalica/micro/templates/micro/register.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/register/" method="post">
<table class="registerTable">
  {% csrf_token %}
  {{ form.as_table }}
</table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/settings.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'micro/style.css' %}" />
  <title>Settings</title>
</head> 
<body>

  <div id="header">

    {% if user.is_authenticated %}
      {{ user.username }}
      <a href="{% url 'micro:logout' %}">Log Out</a>
    {% else %}
      <a href="{% url 'micro:login' %}">Log In</a>
    {% endif %}
    {% block header %}{% endblock header %}

    <nav>
	    
        <ul id = "mainNav">
        <a href="/micro/">
          <li class = "navItem">
            Home
          </li>
        </a>

        <a href="/micro/follow/">
          <li class = "navItem">
            Follow
          </li>
        </a>

        <a href="/micro/settings/">
          <li class = "navItem">
            Settings
          </li>
        </a>


      </ul>
    
    </nav>
  </div>

  <h1 style="text-align: center; padding-bottom: 25px;">Settings Page</h1>

  <h3>What is my user id? </h3>
  <form action="/micro/userid/" method="post">
    {% csrf_token %}
    <select name="userid" id="userid">
        {% for entry in userids %}
            <option value="{{ entry.id }}">{{ entry }}</option>
        {% endfor %}
        </select>
    <input type="submit" value="What is it?" id=submit>
  </form>



  <h3>Add a group</h3>
  <p>Type in the name of the group you want to create</p>
  <form action="/micro/addGroup/" method="post">
    {% csrf_token %}
    <input type=text id=newgroup name=newgroup>
    <input type="submit" value="Submit" id=submit>
  </form>

  <hr/>

  <h3>Delete a group</h3>
  <p>Type in the name of the group you want to delete</p>
  <form action="/micro/grouplist/" method="post">
    {% csrf_token %}
    <input type="submit" value="Click here to then search for the group" id=submit>
    <select name="groups" id="groups">
      {% for entry in items %}
          <option value="{{ entry.id }}">{{ entry }}</option>
      {% endfor %}
      </select>
  </form>
  <form action="/micro/deleteGroup/" method="post">
    {% csrf_token %}
    <p> Type in the name of the group you want to delete here </p>
    <input type=text id=groupp name=groupp>
    <input type="submit" value="Delete" id=submit>
  </form>


  <hr/>


  <h3>Add user to a group</h3>
  <p>What group do you want a member to?</p>

  <form action="/micro/addToGroup/" method="post">
    {% csrf_token %}
    <input type="text" id=groupname1 name=groupname1>

    <p>Who do you want to add to that group, enter the user id?</p>
    <input type="text" id=username1 name=username1>
    <input type="submit" value="Add" id=submit>


    
  </form>
  

  
  
  <hr/>


  <h3>Delete a user from a group</h3>
  <p>First click search, to search the groups</p>
  <form action="/micro/grouplist/" method="post">
    {% csrf_token %}
    <input type="submit" value="Click here to then search for the group" id=submit>
    <select name="groups2" id="groups2">
      {% for entry in items %}
          <option value="{{ entry.id }}">{{ entry }}</option>
      {% endfor %}
      </select>
  </form>
  <p> Then click here to next button to search the users in this group</p>
  <form action="/micro/memberlist/" method="post">
    {% csrf_token %}
    <input type=text id=usersingroup name=usersingroup>
    <input type="submit" value="Click here to then search for the people within the group" id=submit>
    <select name="members" id="members">
      {% for entry in members %}
          <option value="{{ entry.id }}">{{ entry }}</option>
      {% endfor %}
      </select>
  </form>

  <form action="/micro/deleteMember/" method="post">
    {% csrf_token %}
    <p> Then type in the group name here </p>
    <input type=text id=group name=group>
    <p> Then type in the user id here </p>
    <input type=text id=user name=user>
    <input type="submit" value="Delete" id=submit>
  </form>


  



  <div id="sidebar">
    {% block sidebar %}{% endblock sidebar %}
  </div>
  <div id="content">
    {% block content %}{% endblock content %}
  </div>
  <div id="footer">
    <p>Copyright Scalica</p>
    {% block footer %}{% endblock footer %}
  </div>
</body>
</html>

web/scalica/micro/templates/micro/stream.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ stream_user.username }}
{% if form %}
  <form action="/micro/follow/" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_followee" name="followee" value="{{ stream_user.id }}" />
    <input type="submit" value="Follow" />
  </form>
{% endif %}
{% endblock %}
{% block content %}
{% for post in posts %}
  <li>
    {{ post.text }} ({{ post.pub_date|naturaltime }})
  </li>
{% endfor %}
{# TODO: see complete pagination example in Django doc for more #}
{% endblock %}